name: Disable Workflow Video

on:
  push:
    branches: [ main]

jobs: 
  disable:
     runs-on: ubuntu-latest

     steps:
        - name: Rishab Raj
          run: echo "Disable Workflow Video DevOps"
     
